### ISSUE TITLE
Ekzerco 1: Pli ol unu traduka solvo

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/esperanto-kurso-zagreba-metodo#18]
Sur http://esperanto.github.io/esperanto-kurso-zagreba-metodo/html/output/01/ekzerco1/
la maŝino ne akceptas

- lingvisto: Sprachwissenschaftler

Estus bele, se la maŝino akceptus pli ol unu solvon - kaj se la uzanto povus peti akcepton de sia solvo. Simile kiel ĉe Duolingo.

**Comment by Ludoviko2016** [comment]
Dankon, Georg, ke vi enmetis la proponon :)
